version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: